### ISSUE TITLE
html的にヘッダーを追加する

### ISSUE THREAD

**Issue by tetsuyas1** [tetsuyas1/sales_org_survey#16]
ヘッダがなにもないとおかしいので
デザイナにヘッダの作成を依頼しました。
現行のソースにヘッダを追加してほしいです。
追加板ソース
https://github.com/tetsuyas1/sales_org_survey/tree/master/html_source/190208_and-d_html_nouhin

ちなみに、ソース見たけど、下記を追加すれば良さそう。
```html
<header>
		<div class="inner">
			<p>TRIANGLE Scope デモ版</p>
		</div>
</header>
```
```css
.inner{
	max-width: 1000px;
	width: 100%;
	margin: 0 auto;
}

/*=======================================
header
=========================================*/

header{
	padding: 40px 0;
    font-size: 40px;
		color: #ffffff;
	background-image: -webkit-linear-gradient(left, #A5D9C6, #BAE68F);
	background-image: -o-linear-gradient(left, #A5D9C6, #BAE68F);
	background-image: linear-gradient(to right, #A5D9C6, #BAE68F);
}


```
